name: salamtak
description: make getting medication and consultation easier
version: 1.0.0+3
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.5.3
  duration: ^3.0.12
  equatable: ^2.0.5
  file_picker: ^5.2.11
  firebase_auth: ^4.5.0
  firebase_auth_web: ^5.4.0
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  formz: ^0.6.0
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  icon_font_generator: ^3.2.0
  iconsax: ^0.0.8
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.1
  sign_in_with_apple: ^4.3.0
  twilio_flutter: ^0.0.9

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

dependency_overrides:
  intl: 0.18.0

flutter_native_splash:
  background_image: "assets/images/splash.jpg"
  android: true
  ios: true
  web: false

  android_12:
    image: assets/images/salamtak_splash_icon.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#121212"

flutter:
  uses-material-design: true
  generate: true

  fonts:

    - family: UiIcons
      fonts:
        - asset: assets/icons/fonts/ui_icons.ttf

  assets:
    - assets/icons/
    - assets/images/
    - assets/google_fonts/
