name: salamtak
description: make getting medication and consultation easier
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.5.3
  device_preview: ^1.1.0
  duration: ^3.0.12
  equatable: ^2.0.5
  file_picker: ^5.2.11
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  font_awesome: ^5.10.1
  font_awesome_flutter: ^10.4.0
  formz: ^0.6.0
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  iconsax: ^0.0.8
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
