// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG44ijfZqlo2YC7SVxidIKaC6qWgDkUpc',
    appId: '1:47603181237:web:1f9adf73f9dd556f31c0fc',
    messagingSenderId: '47603181237',
    projectId: 'salamtak-kwemrj',
    authDomain: 'salamtak-kwemrj.firebaseapp.com',
    storageBucket: 'salamtak-kwemrj.appspot.com',
    measurementId: 'G-E2Q5Y85LLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu3WnOV0dfuTkyrU5kopYg7PSHwRpo9Ks',
    appId: '1:47603181237:android:1797af536b0a7e7031c0fc',
    messagingSenderId: '47603181237',
    projectId: 'salamtak-kwemrj',
    storageBucket: 'salamtak-kwemrj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeYpG59kKSak6_8t1RbT6EOLxkg-fjrHg',
    appId: '1:47603181237:ios:5e811cc0c65ac24231c0fc',
    messagingSenderId: '47603181237',
    projectId: 'salamtak-kwemrj',
    storageBucket: 'salamtak-kwemrj.appspot.com',
    iosClientId: '47603181237-cfodd8c842o1nf4qudrhm0ice817ltd9.apps.googleusercontent.com',
    iosBundleId: 'com.kwemrj.salamtak.salamtak',
  );
}
